#!/bin/bash
echo "=== Checking HQD Pointers ==="
echo "CP_HQD_PQ_WPTR:"
sudo umr -r *.*.CP_HQD_PQ_WPTR 2>/dev/null || echo "Not found"
echo ""
echo "CP_HQD_PQ_RPTR:" 
sudo umr -r *.*.CP_HQD_PQ_RPTR 2>/dev/null || echo "Not found"
echo ""
echo "CP_SCRATCH0:"
sudo umr -r *.*.CP_SCRATCH0 2>/dev/null || echo "Not found"
echo ""
echo "=== Trying specific ring ==="
echo "gfx_0_0_0 CP_SCRATCH0:"
sudo umr -r gfx_0_0_0.CP_SCRATCH0 2>/dev/null || echo "Not found"